name: Fetch Top Trending Movies

on:
  schedule:
    - cron: "0 */4 * * *"  # chạy mỗi 4 giờ
  workflow_dispatch:        # cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the automation script
      - name: Run fetch script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python ADY201m.py
          
      # Optional: Upload JSON & CSV as workflow artifacts
      - name: Upload JSON & CSV
        uses: actions/upload-artifact@v4
        with:
          name: trending-data
          path: |
            top10_trending_full.json
            top10_trending.csv
